### PR TITLE
remove jquery dependency

### PR DESCRIPTION
**Pull request by tongbin**
Hi @maxkfranz again, I'll also need this plugin without jQuery, which will be great for usage in react/redux frameworks, please review if this's worth for merging back into master project, or there is any problem.

Thanks a lot, you're always quite helpful. ^_^

### CODE REVIEW

**Comment by maxkfranz** [comment]
Since this uses the same approach as you did in edgehandles, we should probably address this first: https://github.com/cytoscape/cytoscape.js-edgehandles/issues/42

**Comment by tongbin** [comment]
@maxkfranz please review this when you've time, thanks very much! It's the same thing what we did in edge handles.

**Comment by maxkfranz** [comment]
@tongbin Thanks.  I won't be able to review this until the 27 October.  Sorry for the delay, but I'll look at it as soon as I'm able.

**Comment by tongbin** [comment]
Thanks for your time, no hurry.

**Comment by maxkfranz** [comment]
@tongbin Sorry for the delay.  I've been really busy.  Can you try with the latest jQuery replacement in [edgehandles](https://github.com/cytoscape/cytoscape.js-edgehandles)?

There's at least this bug that has been fixed in the replacement: https://github.com/cytoscape/cytoscape.js-edgehandles/issues/51

**Pull request closed without merging**
